baseurl = "https://baeharam.github.io"
title = "배하람 블로그"

languageCode = "ko-KR"
DefaultContentLanguage = "kr"
theme = "hugo-hello-programmer-theme"
googleAnalytics = "UA-144188943-1"
paginate = 7

[author]
    name = "배하람"
    email = "hisfedev@gmail.com"

[params]
    description = "개발을 기록하는 블로그"

[permalink]
    posts = "/:filename/"
